name: ci

on:
  pull_request:

jobs:
  test-ko-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.22'
          check-latest: 'true'

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      # Minimal publish
      - uses: ./

      - run: ko publish --bare ./
        if: ${{ github.event_name == 'pull_request' }}
        env:
          KO_DOCKER_REPO: ko.local

      - name: Install old release
        uses: ./
        with:
          version: v0.8.0

      - name: Check installed version
        run: ko version | grep 0.8.0

      - name: Install from tip
        uses: ./
        with:
          version: tip

      - name: Check installed version (tip)
        run: |
          sudo rm /usr/local/bin/ko # Uninstall previous versions.
          ko version

      # If KO_DOCKER_REPO is set during setup, it's set for future steps.
      - name: Pre-set KO_DOCKER_REPO
        uses: ./
        env:
          KO_DOCKER_REPO: already-set

      - name: Check pre-set KO_DOCKER_REPO
        run: |
          if [[ "${KO_DOCKER_REPO}" != "already-set" ]]; then
            echo "${KO_DOCKER_REPO} != already-set"
            exit 1
          fi
