name: ci

on:
  pull_request:

jobs:
  test-ko-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '1.22'
          check-latest: 'true'

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # Minimal publish
      - uses: ./

      - run: ko publish --bare ./
        if: ${{ github.event_name == 'pull_request' }}
        env:
          KO_DOCKER_REPO: ko.local

      - name: Install old release
        uses: ./
        with:
          version: v0.8.0

      - name: Check installed version
        run: ko version | grep 0.8.0

      - name: Install from tip
        uses: ./
        with:
          version: tip

      - name: Check installed version (tip)
        run: |
          sudo rm /usr/local/bin/ko # Uninstall previous versions.
          ko version

      # If KO_DOCKER_REPO is set during setup, it's set for future steps.
      - name: Pre-set KO_DOCKER_REPO
        uses: ./
        env:
          KO_DOCKER_REPO: already-set

      - name: Check pre-set KO_DOCKER_REPO
        run: |
          if [[ "${KO_DOCKER_REPO}" != "already-set" ]]; then
            echo "${KO_DOCKER_REPO} != already-set"
            exit 1
          fi
