name: Use Action

on:
  push:
    branches:
      - 'main'

jobs:
  use-action:
    name: Use Action

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.20'
          check-latest: 'true'

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      # Minimal publish
      - uses: ko-build/setup-ko@main

      - run: ko publish --bare ./

      - name: Install old release
        uses: ko-build/setup-ko@main
        with:
          version: v0.8.0

      - name: Check installed version
        run: ko version | grep 0.8.0

      - name: Install from tip
        uses: ko-build/setup-ko@main
        with:
          version: tip

      - name: Check installed version (tip)
        run: |
          sudo rm /usr/local/bin/ko # Uninstall previous versions.
          ko version

      # If KO_DOCKER_REPO is set during setup, it's set for future steps.
      - name: Pre-set KO_DOCKER_REPO
        uses: ko-build/setup-ko@main
        env:
          KO_DOCKER_REPO: already-set

      - name: Check pre-set KO_DOCKER_REPO
        run: |
          if [[ "${KO_DOCKER_REPO}" != "already-set" ]]; then
            echo "${KO_DOCKER_REPO} != already-set"
            exit 1
          fi
